<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Word.Core\EnWord.Core.csproj" />
    <ProjectReference Include="..\Word.DataAccess\EnWord.DataAccess.csproj" />
  </ItemGroup>

</Project>
