<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>30d01296-6532-481f-8fe0-2592968fc628</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
    <PackageReference Include="NRedisStack" Version="1.1.0" />
    <PackageReference Include="StackExchange.Redis" Version="2.9.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EnWord.Application\EnWord.Application.csproj" />
    <ProjectReference Include="..\Word.Core\EnWord.Core.csproj" />
    <ProjectReference Include="..\Word.DataAccess\EnWord.DataAccess.csproj" />
  </ItemGroup>

</Project>
